//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_GTS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characteristic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Characteristic()
        {
            this.CharacteristicValue = new HashSet<CharacteristicValue>();
        }
    
        public int CharactID { get; set; }
        public string CharactName { get; set; }
        public string CharactDataType { get; set; }
        public string CharactDefaultUnit { get; set; }
        public string CharactDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacteristicValue> CharacteristicValue { get; set; }
    }
}
