//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_GTS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacteristicValue
    {
        public int ValueID { get; set; }
        public int ValueSizeID { get; set; }
        public int ValueCharactID { get; set; }
        public string ValuePrecisionType { get; set; }
        public string ValueToleranceDirection { get; set; }
        public Nullable<decimal> ValueTolerance { get; set; }
        public Nullable<decimal> ValueNumeric { get; set; }
        public string ValueString { get; set; }
        public string ValueUnit { get; set; }
    
        public virtual Characteristic Characteristic { get; set; }
        public virtual Size Size { get; set; }
    }
}
