//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_GTS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int FavoriteID { get; set; }
        public int FavoriteUserID { get; set; }
        public int FavoriteProductSizeID { get; set; }
        public Nullable<System.DateTime> FavoriteCreate { get; set; }
        public string FavoriteFolderName { get; set; }
    
        public virtual Size Size { get; set; }
        public virtual User User { get; set; }
    }
}
